#!/usr/bin/env bun
/**
 * Embed all guideline data into a TypeScript file for bundling into binary.
 * Run: bun run scripts/embed-data.ts
 */

import { readFile, readdir, writeFile } from 'fs/promises';
import { join } from 'path';
import YAML from 'yaml';

interface GuidelineMapping {
  path: string;
  languages?: string[];
  levels?: string[];
  architectures?: string[];
  tags?: string[];
}

interface EmbeddedData {
  mappings: Record<string, GuidelineMapping>;
  guidelines: Record<string, string>;
}

async function readGuidelinesRecursively(dir: string, basePath: string = ''): Promise<Record<string, string>> {
  const guidelines: Record<string, string> = {};
  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    const relativePath = basePath ? `${basePath}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      const subGuidelines = await readGuidelinesRecursively(fullPath, relativePath);
      Object.assign(guidelines, subGuidelines);
    } else if (entry.name.endsWith('.md')) {
      const content = await readFile(fullPath, 'utf-8');
      guidelines[relativePath] = content;
    }
  }

  return guidelines;
}

async function embedData() {
  console.log('📦 Embedding guideline data into TypeScript...\n');

  const dataDir = join(process.cwd(), 'data');
  const mappingsPath = join(dataDir, 'guideline-mappings.yml');

  // Read mappings
  const mappingsContent = await readFile(mappingsPath, 'utf-8');
  const mappings = YAML.parse(mappingsContent) as Record<string, GuidelineMapping>;

  console.log(`  Loaded ${Object.keys(mappings).length} guideline mappings`);

  // Read all guidelines from data directory
  const guidelines = await readGuidelinesRecursively(dataDir);

  // Remove the mappings file and top-level index from guidelines
  delete guidelines['guideline-mappings.yml'];
  delete guidelines['index.md'];

  console.log(`  Loaded ${Object.keys(guidelines).length} markdown files`);

  const data: EmbeddedData = { mappings, guidelines };

  // Generate TypeScript file
  const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/embed-data.ts
// Contains all guideline mappings and content embedded for binary distribution

export interface GuidelineMapping {
  path: string;
  category?: string;
  languages?: string[];
  levels?: string[];
  architectures?: string[];
  tags?: string[];
}

export interface EmbeddedData {
  mappings: Record<string, GuidelineMapping>;
  guidelines: Record<string, string>;
}

export const EMBEDDED_DATA: EmbeddedData = ${JSON.stringify(data, null, 2)};

export const GUIDELINE_COUNT = ${Object.keys(guidelines).length};
export const MAPPING_COUNT = ${Object.keys(mappings).length};
`;

  const outputPath = join(process.cwd(), 'src', 'embedded-data.ts');
  await writeFile(outputPath, output, 'utf-8');

  const sizeKB = (output.length / 1024).toFixed(1);
  console.log(`\n✅ Generated src/embedded-data.ts (${sizeKB} KB)`);
  console.log(`   ${Object.keys(mappings).length} mappings, ${Object.keys(guidelines).length} guidelines embedded`);
}

embedData().catch(err => {
  console.error('❌ Failed to embed data:', err);
  process.exit(1);
});
